import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";
import clsx from "clsx";
import MainLayout from "@/layout";
import NextTopLoader from "nextjs-toploader";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = localFont({
  src: [
    {
      path: "../../public/fonts/lato/lato-extra-bold.ttf",
      weight: "800",
    },
    {
      path: "../../public/fonts/lato/lato-bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/lato/lato-medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/lato/lato-regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-lato",
});

const helvetica = localFont({
  src: [
    {
      path: "../../public/fonts/helvetica/helvetica-bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-helvetica",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(lato.variable, helvetica.variable)}>
        <NextTopLoader
          color="#FF6813"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #FF6813,0 0 5px #FF6813"
        />
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
