import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "@/styles/globals.css";
import clsx from "clsx";
import MainLayout from "@/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = localFont({
  src: [
    {
      path: "../../public/fonts/lato/lato-extra-bold.ttf",
      weight: "800",
    },
    {
      path: "../../public/fonts/lato/lato-bold.ttf",
      weight: "700",
    },
    {
      path: "../../public/fonts/lato/lato-medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/lato/lato-regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-lato",
});

const helvetica = localFont({
  src: [
    {
      path: "../../public/fonts/helvetica/helvetica-bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-helvetica",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(lato.variable, helvetica.variable)}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
